plugins:
  - serverless-offline
  - serverless-plugin-typescript-express

service: express-mongodb-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2  	

functions:
  app:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
